services:
  - type: web
    name: property-pricing-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    port: 8000
    plan: free

  - type: web
    name: property-pricing-streamlit
    runtime: docker
    dockerfilePath: ./Dockerfile.streamlit
    port: 8501
    plan: free
    envVars:
      - key: API_URL
        value: https://property-pricing-pl.onrender.com
